// data.js — single source of truth for the DUBEL ART catalogue.
// Edit via admin.html, then Export this file and re-upload to publish.
window.SITE = {
  "name": "DUBEL ART",
  "wordmarkA": "DUBEL",
  "wordmarkB": "ART",
  "tagline": "Dubel Team — Art Department",
  "email": "",
  "phone": "",
  "address": "",
  "url": "art.dubel.team",
  "ticker": [
    "PRIVATE SALE",
    "DUBEL TEAM — ART DEPARTMENT",
    "MODERN & CONTEMPORARY MASTERS",
    "RARE & COLLECTIBLE WORKS",
    "BY APPOINTMENT",
    "WORLDWIDE SHIPPING",
    "PROVENANCE ON REQUEST"
  ],
  "heroEyebrow": "DUBEL TEAM — ART DEPARTMENT · PRIVATE SALE",
  "heroLine1": "RARE",
  "heroLine2": "MODERN",
  "heroLine3": "MASTERS.",
  "heroStatement": "A privately held group of modern & contemporary works, presented by the Dubel Team Art Department.",
  "heroBody": "Fourteen paintings, prints and sculptures spanning a century of modern art — each acquired with discernment, documented with provenance, and offered privately to a select international clientele. Viewings and condition reports by appointment.",
  "adminPass": "dubel-art-2026",
  "currencyDefault": "EUR",
  "formProvider": "web3forms",
  "formEndpoint": "https://api.web3forms.com/submit",
  "formAccessKey": "",
  "priceNote": "All prices are in EUR and exclude shipping, handling, insurance and any taxes or import duties. Final pricing may vary with the buyer's location and local tax treatment.",
  "priceHiddenLabel": "Contact for price",
  "dataVersion": 1782294848364,
  "logo": "images/logo.png"
};

window.ARTWORKS = [
  {
    "slug": "gotsch-red-house-on-the-beach",
    "artist": "Friedrich Karl Gotsch",
    "title": "Red House on the Beach",
    "year": "1928",
    "medium": "Oil on canvas",
    "dimensions": "47.8 × 63.4 cm",
    "price": "€15,000",
    "priceSort": 15000,
    "featured": true,
    "signature": "Unsigned",
    "condition": "Excellent — frame changed",
    "internalNote": "Source: Mostar, BiH. Internal reference: €15,000.",
    "description": "An Expressionist beach scene by the German painter Friedrich Karl Gotsch, a pupil of Karl Schmidt-Rottluff. A vivid red house sits among wind-bent trees and traditional German strandkörbe (hooded beach chairs), rendered in the bold outline and saturated colour of the Brücke tradition.",
    "provenance": [
      "Private Collection, Germany, 2010",
      "Art 1900, Fine Art & Fine Jewels, 31/03/2022",
      "Dubel Team — Art Department"
    ],
    "publications": [
      "Goeritz, Leuba & Rathke, Friedrich Karl Gotsch 1900–1984: Werkverzeichnis der Gemälde, 1993, p. 73"
    ],
    "exhibitions": [],
    "status": "available",
    "priceMode": "value",
    "framed": "",
    "image": "images/gotsch-red-house-on-the-beach.jpg",
    "thumb": "images/gotsch-red-house-on-the-beach-thumb.jpg",
    "id": 1
  },
  {
    "slug": "fogel-skeletal-structure",
    "artist": "Seymour Fogel",
    "title": "Skeletal Structure",
    "year": "1947",
    "medium": "Oil on canvas",
    "dimensions": "76.2 × 101.6 cm",
    "price": "€15,200",
    "priceSort": 15200,
    "featured": true,
    "signature": "Signed lower right, “Fogel 47”",
    "condition": "Very Good — frame changed",
    "internalNote": "Source: Koller, Zurich, Switzerland. Internal reference: CHF 12,000–14,000.",
    "description": "A structural abstraction by the American modernist Seymour Fogel, a former assistant to Diego Rivera and a noted muralist of the WPA era. Architectural grids of yellow, grey and oxblood interlock like the framing of a building stripped to its skeleton.",
    "provenance": [
      "Modernism Fine Art Inc, New York",
      "Dubel Team — Art Department"
    ],
    "publications": [],
    "exhibitions": [],
    "status": "available",
    "priceMode": "value",
    "framed": "",
    "image": "images/fogel-skeletal-structure.jpg",
    "thumb": "images/fogel-skeletal-structure-thumb.jpg",
    "id": 2
  },
  {
    "slug": "titov-fallen-man-and-the-angel",
    "artist": "Vladimir Titov",
    "title": "Fallen Man and the Angel",
    "year": "",
    "medium": "Oil on canvas",
    "dimensions": "97 × 130 cm",
    "price": "€6,000",
    "priceSort": 6000,
    "featured": true,
    "signature": "",
    "condition": "Excellent",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €6,000.",
    "description": "A heavily impastoed, almost relief-like composition in earth and slate tones. Two intertwined figures — the fallen man and the angel — emerge from a densely worked, tactile surface that blurs the line between painting and sculpture.",
    "provenance": [
      "Artist Estate",
      "Private Collection, Irina Kuznetzova",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "exhibitions": [],
    "publications": [],
    "framed": "",
    "image": "images/titov-fallen-man-and-the-angel.jpg",
    "thumb": "images/titov-fallen-man-and-the-angel-thumb.jpg",
    "id": 3
  },
  {
    "slug": "denny-man-in-water",
    "artist": "Bruce Denny",
    "title": "Man In Water",
    "year": "2021",
    "medium": "Crystal clear resin",
    "dimensions": "65 × 40 × 30 cm",
    "edition": "Edition AP1",
    "price": "€7,000",
    "priceSort": 7000,
    "featured": true,
    "signature": "",
    "condition": "Excellent",
    "internalNote": "Source: Mostar, BiH. Internal reference: €6,000–7,000.",
    "description": "A male figure emerging from a fluid, wave-like base, creating a striking tension between solidity and dissolution. The highly reflective resin transforms the body into a play of light and distorted reflection, with the arms placed behind the head recalling both the classical nude and a contemporary study of vulnerability and self-awareness.",
    "provenance": [
      "Bruce Denny, UK",
      "Tim Plateaux, September 2022, UK",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "exhibitions": [],
    "publications": [],
    "framed": "",
    "image": "images/denny-man-in-water.jpg",
    "thumb": "images/denny-man-in-water-thumb.jpg",
    "id": 4
  },
  {
    "slug": "denny-ripped",
    "artist": "Bruce Denny",
    "title": "Ripped",
    "year": "2021",
    "medium": "Bronze",
    "dimensions": "110 × 50 × 30 cm",
    "price": "€7,000",
    "priceSort": 7000,
    "signature": "",
    "condition": "Excellent",
    "internalNote": "Source: Mostar, BiH. Internal reference: €6,000–7,000.",
    "description": "A standing male nude rendered with strong anatomical observation and emotional introspection. The figure's downward gaze and the gesture of opening the chest introduce a symbolic exploration of vulnerability and self-examination. Set on a dark geometric base that emphasises verticality and isolation.",
    "provenance": [
      "Bruce Denny, UK",
      "Tim Plateaux, September 2022, UK",
      "Dubel Team — Art Department"
    ],
    "exhibitions": [],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "publications": [],
    "framed": "",
    "image": "images/denny-ripped.jpg",
    "thumb": "images/denny-ripped-thumb.jpg",
    "id": 5
  },
  {
    "slug": "chabaud-autour-de-la-table",
    "artist": "Auguste Chabaud",
    "title": "Autour de la table",
    "year": "",
    "medium": "Mixed media on cardboard",
    "dimensions": "54 × 76.5 cm",
    "framed": "71.8 × 94.7 cm",
    "price": "€5,500",
    "priceSort": 5500,
    "featured": true,
    "signature": "Signed lower left, “A. CHABAUD”",
    "condition": "Very Good",
    "internalNote": "Source: Artcurial, Paris, France. Internal reference: €4,500–5,500.",
    "description": "A nocturnal interior by the French Fauve and Expressionist Auguste Chabaud, built from heavy black contours and electric acid-green light. Figures gather around a table in a composition that recalls Chabaud's Montmartre cabaret scenes of the early 1900s.",
    "provenance": [
      "Artist Estate",
      "Thierry de Maigret — Prints, Paintings & Sculptures of the 19th & 20th centuries / Art Nouveau, 7/12/2022",
      "Dubel Team — Art Department"
    ],
    "publications": [
      "Semenova, From Bohemianism to Eternity: The Splendour of Modern Art 1900s–1970s, April 2024, pp. 112–113"
    ],
    "exhibitions": [
      "From Bohemianism to Eternity: The Splendour of Modern Art 1900s–1970s, Gallery Klovićevi Dvori, Zagreb, 14 May 2024"
    ],
    "status": "available",
    "priceMode": "value",
    "image": "images/chabaud-autour-de-la-table.jpg",
    "thumb": "images/chabaud-autour-de-la-table-thumb.jpg",
    "id": 6
  },
  {
    "slug": "ireland-composition",
    "artist": "Lucille Ireland",
    "title": "Composition",
    "year": "1938",
    "medium": "Oil on canvas",
    "dimensions": "91 × 76 cm",
    "price": "€2,500",
    "priceSort": 2500,
    "signature": "Signed lower right, “L Ireland”",
    "condition": "Excellent — frame changed",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €2,500.",
    "description": "A geometric, Neo-Plasticist composition of interlocking colour fields and black bars. Lucille Ireland was the most avant-garde painter of the New Hope Modernist Group. Born in Lambertville, Pennsylvania in 1888, she moved to New York in 1908 to study at the Art Students League, and lived in Manhattan throughout the 1920s, supporting herself primarily as a fashion illustrator.",
    "provenance": [
      "Estate of the Artist",
      "Private Collection, New Hope, Pennsylvania",
      "Private Collection, Lambertville, Pennsylvania",
      "Auerbach and Maffia, Fountainville, Pennsylvania",
      "Modernism Fine Arts Inc, New York",
      "Dubel Team — Art Department"
    ],
    "exhibitions": [],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "publications": [],
    "framed": "",
    "image": "images/ireland-composition.jpg",
    "thumb": "images/ireland-composition-thumb.jpg",
    "id": 7
  },
  {
    "slug": "meroville-landscape-trees-lake",
    "artist": "Claude Meroville",
    "title": "Landscape with Trees by the Lake",
    "year": "1933",
    "medium": "Oil on canvas",
    "dimensions": "60 × 90 cm",
    "price": "€2,500",
    "priceSort": 2500,
    "signature": "Signed and dated lower right, “C Meroville 1933”",
    "condition": "Excellent",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €2,500.",
    "description": "A Pointillist-inflected landscape of trees mirrored in a still lake, built from a dense mosaic of broken colour. The rounded, blossoming forms of the foliage are set against a softly divided sky and water.",
    "provenance": [
      "Galerie Poncé, St. Paul de Vence, France",
      "Private Collection, France",
      "Kenneth J. Dukoff, Inc, Buffalo / Niagara, New York",
      "Acquired by the present owner from the above",
      "Modernism Fine Art Inc, New York",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "publications": [],
    "framed": "",
    "image": "images/meroville-landscape-trees-lake.jpg",
    "thumb": "images/meroville-landscape-trees-lake-thumb.jpg",
    "id": 8
  },
  {
    "slug": "golubov-untitled-1946",
    "artist": "Maurice Golubov",
    "title": "Untitled",
    "year": "1946",
    "medium": "Oil on wood panel",
    "dimensions": "27.9 × 43.1 cm",
    "price": "€2,500",
    "priceSort": 2500,
    "signature": "Signed lower left, “M. Golubov 46”",
    "condition": "Very Good",
    "internalNote": "Source: Mostar, BiH. Internal reference: €2,500.",
    "description": "A densely layered abstraction in midnight blue, ochre and rose by the Russian-born American modernist Maurice Golubov. Geometric and gestural elements are woven into an all-over field that hovers between figuration and pure abstraction.",
    "provenance": [
      "Artist's Estate",
      "The Art Students League, New York",
      "Acquired from the above by the current owner, 1996",
      "Modernism Fine Art Inc, New York",
      "Dubel Team — Art Department"
    ],
    "publications": [],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "framed": "",
    "image": "images/golubov-untitled-1946.jpg",
    "thumb": "images/golubov-untitled-1946-thumb.jpg",
    "id": 9
  },
  {
    "slug": "deliotti-street-scenes",
    "artist": "Walter Deliotti",
    "title": "Street Scenes",
    "year": "",
    "medium": "Oil on canvas",
    "dimensions": "25 × 20 cm",
    "price": "€1,500",
    "priceSort": 1500,
    "signature": "Signed lower right",
    "condition": "Excellent",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €1,500.",
    "description": "A compact, cubist-influenced port scene crowded with market stalls, rooftops and figures. Bold black outlines and flat planes of muted colour compress the architecture of a harbour town into a tightly interlocking composition.",
    "provenance": [
      "Galería Valle Orti, Valencia",
      "La Habana Subastas, Madrid",
      "Durán Arte y Subastas, Auction 614, Lot 300, 25/11/2022",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "publications": [],
    "framed": "",
    "image": "images/deliotti-street-scenes.jpg",
    "thumb": "images/deliotti-street-scenes-thumb.jpg",
    "id": 10
  },
  {
    "slug": "canovas-unknown",
    "artist": "Ernesto Cánovas",
    "title": "Untitled",
    "year": "2012",
    "medium": "Mixed media",
    "dimensions": "45 × 63 cm",
    "price": "€1,500",
    "priceSort": 1500,
    "signature": "",
    "condition": "Excellent",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €1,500.",
    "description": "A contemporary mixed-media work by the Spanish artist Ernesto Cánovas, layering a found palm-lined mountain landscape beneath washes of resin and pigment. The faded, photographic image surfaces through a warm amber veil, suspended between memory and decay.",
    "provenance": [
      "Artist Estate",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "publications": [],
    "framed": "",
    "image": "images/canovas-unknown.jpg",
    "thumb": "images/canovas-unknown-thumb.jpg",
    "id": 11
  },
  {
    "slug": "miot-geometric-composition",
    "artist": "Maurice Melito Miot",
    "title": "Geometric Composition",
    "year": "",
    "medium": "Oil on canvas",
    "dimensions": "74 × 93 cm",
    "framed": "79 × 98 cm",
    "price": "€1,300",
    "priceSort": 1300,
    "signature": "Signed on the reverse",
    "condition": "Good",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €1,000–1,300.",
    "description": "A white rectangle is dominantly placed on a brown ground. Over it, black, olive, green and red triangles face one another in sharp opposition. The surfaces are monolithic and the palette is muted — a hard-edged study in geometric tension.",
    "provenance": [
      "Le Floc'h Auction House, 02/02/2023",
      "Dubel Team — Art Department"
    ],
    "publications": [
      "Semenova, From Bohemianism to Eternity: The Splendour of Modern Art 1900s–1970s, April 2024, pp. 238–239"
    ],
    "exhibitions": [
      "From Bohemianism to Eternity: The Splendour of Modern Art 1900s–1970s, Gallery Klovićevi Dvori, Zagreb, 14 May 2024"
    ],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "image": "images/miot-geometric-composition.jpg",
    "thumb": "images/miot-geometric-composition-thumb.jpg",
    "id": 12
  },
  {
    "slug": "schanker-untitled-1942",
    "artist": "Louis Schanker",
    "title": "Untitled",
    "year": "1942",
    "medium": "Oil and sand on canvas",
    "dimensions": "50.8 × 61 cm",
    "price": "€1,100",
    "priceSort": 1100,
    "signature": "Signed lower right, “Schanker”",
    "condition": "Excellent",
    "internalNote": "Source: Koller, Zurich, Switzerland. Internal reference: CHF 800–1,000.",
    "description": "Three abstract anthropomorphic figures, their forms inspired by tribal art, dominate the composition. A cobalt-blue ground throws the green, red and yellow figures forward so that they seem to move together in a group dance.",
    "provenance": [
      "Studio of the Artist",
      "Ruth O'Hara Gallery, New York",
      "Jem Hom Fine Arts, Washington, D.C.",
      "Acquired from the above by the present owner, 1993",
      "Dubel Team — Art Department"
    ],
    "publications": [],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "framed": "",
    "image": "images/schanker-untitled-1942.jpg",
    "thumb": "images/schanker-untitled-1942-thumb.jpg",
    "id": 13
  },
  {
    "slug": "makarevich-seagull",
    "artist": "Igor Makarevich",
    "title": "Seagull",
    "year": "1991",
    "medium": "Screen print",
    "dimensions": "73 × 53 cm",
    "framed": "67 × 88 cm",
    "price": "€800",
    "priceSort": 800,
    "signature": "Signed",
    "condition": "Excellent",
    "internalNote": "Source: Hampel, Munich, Germany. Internal reference: €800.",
    "description": "A screen print by Igor Makarevich, a leading figure of Moscow Conceptualism, layering gestural blue and ochre marks with passages of Cyrillic handwriting around a central luminous form. From the artist's reflections on Chekhov's The Seagull.",
    "provenance": [
      "Artist Estate",
      "Auction house Litfond",
      "Dubel Team — Art Department"
    ],
    "status": "available",
    "priceMode": "value",
    "featured": false,
    "exhibitions": [],
    "publications": [],
    "image": "images/makarevich-seagull.jpg",
    "thumb": "images/makarevich-seagull-thumb.jpg",
    "id": 14
  },
  {
    "slug": "boem",
    "artist": "BOEM",
    "title": "Continuous Line",
    "year": "2020",
    "medium": "Spray paint & acrylic, framed",
    "dimensions": "",
    "framed": "",
    "edition": "",
    "price": "€1,500",
    "priceSort": 1500,
    "priceMode": "value",
    "status": "available",
    "featured": false,
    "signature": "",
    "condition": "",
    "description": "A bold contemporary work in which a single, unbroken black line traces an abstracted face. Set against a sprayed wash of pink, ochre and white, the composition is punctuated by a vivid red mouth, a single stylised eye and a raised hand — a meeting of graffiti energy and continuous-line drawing. Presented in a vintage gilt frame.",
    "provenance": [
      "Dubel Team — Art Department"
    ],
    "exhibitions": [],
    "publications": [],
    "internalNote": "",
    "image": "images/boem.jpg",
    "thumb": "images/boem-thumb.jpg",
    "id": 15
  },
  {
    "slug": "mauro",
    "artist": "MAURO",
    "title": "City Muse",
    "year": "2025",
    "medium": "Acrylic on canvas",
    "dimensions": "",
    "framed": "",
    "edition": "",
    "price": "€800",
    "priceSort": 800,
    "priceMode": "value",
    "status": "available",
    "featured": false,
    "signature": "",
    "condition": "",
    "description": "A vibrant figurative composition centred on a woman with a full afro and oversized gold hoop earrings, her gaze direct and self-possessed. Behind her rises an expressionistic city of saturated towers and bridges, with a small seated figure at the right edge. The naïve, high-colour handling recalls outsider and neo-expressionist painting.",
    "provenance": [
      "Dubel Team — Art Department"
    ],
    "exhibitions": [],
    "publications": [],
    "internalNote": "",
    "image": "images/mauro.jpg",
    "thumb": "images/mauro-thumb.jpg",
    "id": 16
  },
  {
    "slug": "pngs",
    "artist": "PNGS",
    "title": "Fracture",
    "year": "2018",
    "medium": "Acrylic, spray paint & mixed media on canvas",
    "dimensions": "",
    "framed": "",
    "edition": "",
    "price": "€1,500",
    "priceSort": 1500,
    "priceMode": "value",
    "status": "available",
    "featured": false,
    "signature": "Signed lower left, “PNGS”",
    "condition": "",
    "description": "A brooding mixed-media portrait of a hooded figure whose face dissolves into a shattered, mosaic-like burst of metallic and coloured fragments. Drips of white and washes of black and blue lend a weathered, urban surface, playing on themes of identity, anonymity and fragmentation.",
    "provenance": [
      "Dubel Team — Art Department"
    ],
    "exhibitions": [],
    "publications": [],
    "internalNote": "",
    "image": "images/pngs.jpg",
    "thumb": "images/pngs-thumb.jpg",
    "id": 17
  }
];
